---
- name: Create directories needed for logging if they do not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  with_items:
    - "/data/logs/traefik"
    - "/data/logs/nextcloud"
    - "/data/logs/keycloak"


- name: Create file needed for keycloak logging
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: '0777'
  with_items:
    - "/data/logs/keycloak/keycloak.log"
    - "/data/logs/nextcloud/nextcloud.log"

- name: Deploy stack from a compose file
  docker_stack:
    state: present
    name: VCC_stack
    compose:
      - "{{ playbook_dir }}/docker-compose.yml"