---
- name: Create directories needed for logging if they do not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  with_items:
    - "{{ playbook_dir }}/logs/traefik"
    - "{{ playbook_dir }}/logs/nextcloud"
    - "{{ playbook_dir }}/logs/keycloak"


- name: Create file needed for keycloak logging
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: '0777'
  with_items:
    - "{{ playbook_dir }}/logs/keycloak/keycloak.log"

- name: Deploy stack from a compose file
  docker_stack:
    state: present
    name: VCC_stack
    compose:
      - "{{ playbook_dir }}/docker-compose.yml"

- name: Adding entry to trusted domains
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/data/nextcloud/config/config.php"
    insertafter: 0 => 'localhost',
    line: 1 => '192.168.50.10',

- name: restart service
  community.docker.docker_compose:
    definition: "{{ playbook_dir }}/docker-compose.yml"  
    state: restarted