---
- name: "Render docker-compose file using variables"
  ansible.builtin.template:
    src: "{{ playbook_dir }}/docker-compose.j2"
    dest: "/docker-compose.yml"
    mode: '0777'

- name: Deploy stack from a compose file
  community.docker.docker_stack:
    state: present
    name: VCC_stack
    with_registry_auth: true
    compose:
      - "/docker-compose.yml"
