---
- name: Create directories needed for logging and data persistance if they do not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  with_items:
    - "{{ nfs_share_path }}/logs/traefik"
    - "{{ nfs_share_path }}/logs/nextcloud"
    - "{{ nfs_share_path }}/logs/keycloak"
    - "{{ nfs_share_path }}/loki"
    - "{{ nfs_share_path }}/prometheus"
    - "{{ nfs_share_path }}/grafana"
    - "{{ nfs_share_path }}/volumes"

- name: Create file needed for keycloak logging
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: '0777'
  with_items:
    - "{{ nfs_share_path }}/logs/keycloak/keycloak.log"
    - "{{ nfs_share_path }}/logs/nextcloud/nextcloud.log"

- name: Copy dir with entrypoints
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/volumes"
    dest: "{{ shared_volumes }}"
    mode: '0777'

- name: "Render realm.json file using variables"
  template:
    src: "{{ shared_volumes }}/keycloak/realm.j2"
    dest: "{{ shared_volumes }}/keycloak/realm.json"
    mode: '0777'

- name: "Render prometheus.yml file using variables"
  template:
    src: "{{ shared_volumes }}/prometheus/prometheus.j2"
    dest: "{{ shared_volumes }}/prometheus/prometheus.yml"
    mode: '0777'