{
 "title": "Logs_dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Fluent bit logs 1",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"node1\"} |= `fluentbit`"
    }
   ]
  },
  {
   "title": "Fluent bit logs 2",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"node2\"} |= `fluentbit`"
    }
   ]
  },
  {
   "title": "Grafana logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{host=\"node1\"} |= `grafana`"
    },
    {
     "expr": "{host=\"node2\"} |= `grafana`"
    }
   ]
  },
  {
   "title": "Nextcloud logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{host=\"node1\"} |= `nextcloud`"
    },
    {
     "expr": "{host=\"node2\"} |= `nextcloud`"
    }
   ]
  },
  {
   "title": "Prometheus logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{host=\"node1\"} |= `prometheus`"
    },
    {
     "expr": "{host=\"node2\"} |= `prometheus`"
    }
   ]
  },
  {
   "title": "Keycloak logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{host=\"node1\"} |= `keycloak`"
    },
    {
     "expr": "{host=\"node2\"} |= `keycloak`"
    }
   ]
  },
  {
   "title": "Loki logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{host=\"node1\"} |= `loki`"
    },
    {
     "expr": "{host=\"node2\"} |= `loki`"
    }
   ]
  },
  {
   "title": "Postgres logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{host=\"node1\"} |= `postgres`"
    },
    {
     "expr": "{host=\"node2\"} |= `postgres`"
    }
   ]
  },
  {
   "title": "Registry logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{host=\"node1\"} |= `registry`"
    }
   ]
  },
  {
   "title": "Traefik logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "{host=\"node1\"} |= `traefik`"
    },
    {
     "expr": "{host=\"node2\"} |= `traefik`"
    }
   ]
  }
 ]
}