---
- name: Erase keycloak image in order to re-execute entrypoint
  community.docker.docker_image:
    build:
      path: "{{ shared_volumes }}/keycloak/container/"
      nocache: true
    name: "{{ registry_url }}:{{ registry_port }}/keycloak"
    source: build
    state: absent
    force_absent: true

- name: Build an image and push it to a private repo
  community.docker.docker_image:
    build:
      path: "{{ shared_volumes }}/keycloak/container/"
      nocache: true
    name: "{{ registry_url }}:{{ registry_port }}/keycloak"
    push: true
    source: build
    debug: true