---
- name: Deploy keycloak instance
  community.docker.docker_swarm_service:
    name: keycloak
    image: quay.io/keycloak/keycloak:20.0.1
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.role == manager
    networks:
      - name: host
    args:
      - start-dev
    mode: replicated
    replicas: 1
    env:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_DB: postgres 
      KC_DB_URL: jdbc:postgresql://10.255.255.10:5432/keycloak 
      KC_DB_PASSWORD: keycloak 
      KC_DB_USERNAME: keycloak
    