version: "3.8"
services:
  postgres:
    image: postgres:15.1
    environment: 
      POSTGRES_DB: vcc-test
      POSTGRES_USER: vcc-test
      POSTGRES_PASSWORD: vcc-test
    volumes:
      - /data/postgresql/data_dir:/var/lib/postgresql/data
      - /data/postgresql/sql:/docker-entrypoint-initdb.d
    networks:
      - traefik-public
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.role==manager"
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - target: 5432
        published: 5432
        mode: host

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: VCC_stack_keycloak
    command: 
      - start-dev
      - --log-level=debug
      - --log=console,file
      - --log-file=/logs/keycloak.log
    environment: 
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_DB: postgres 
      KC_DB_URL: jdbc:postgresql://10.255.255.10:5432/keycloak 
      KC_DB_PASSWORD: keycloak 
      KC_DB_USERNAME: keycloak
    depends_on:
      - postgres
    volumes:
      - ./logs/keycloak/keycloak.log:/logs/keycloak.log
    networks:
      - traefik-public
    #ports:
    #  - "8081:8080"  
    #ports:
    #  - target: 591
    #    published: 591
    #    mode: host
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.role==manager"
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # Change the host url here
        - "traefik.http.routers.keycloak.rule=Host(`auth.localdomain`)"
        - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
        #- "traefik.http.routers.nextcloud.middlewares=auth"
        - "traefik.http.routers.keycloak.entrypoints=web"
        - "traefik.docker.network=VCC_stack_default"
        - traefik.http.services.keycloak.loadbalancer.sticky=true
        - traefik.http.services.keycloak.loadbalancer.sticky.cookie.name=KeycloakCookie
        #- "traefik.http.routers.keycloak.tls=true"
        #- "traefik.http.routers.keycloak.tls.certresolver=leresolver"
        #- "traefik.http.routers.nextcloud_route.tls=true"
        #- "traefik.http.routers.keycloak.middlewares=keycloak_proto"
        #- "traefik.http.services.VCC_stack_nextcloud.loadbalancer.server.port=8081"
        #- "traefik.http.middlewares.keycloak_proto.headers.customrequestheaders.X-Forwarded-Proto=https"   

  nextcloud:
    image: nextcloud:23.0-apache
    environment: 
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud
      POSTGRES_HOST: 10.255.255.10
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
    volumes:
      - /data/nextcloud:/var/www/html
      - ./logs/nextcloud/nextcloud.log:/nextcloud.log
    depends_on:
      - postgres 
    networks:
      - traefik-public
    #ports:
    #  - 6081:80 
    #ports:
    #  - target: 8008
    #    published: 8008
    #    mode: host
    #networks:
    #  - traefik-public
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.role==manager"
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # Change the host url here
        - "traefik.http.routers.nextcloud.rule=Host(`cloud.localdomain`)"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
        #- "traefik.port=8080"
        #- "traefik.http.routers.nextcloud.middlewares=auth"
        - "traefik.http.routers.nextcloud.entrypoints=web"
        - "traefik.docker.network=VCC_stack_default"
        - traefik.http.services.nextcloud.loadbalancer.sticky=true
        - traefik.http.services.nextcloud.loadbalancer.sticky.cookie.name=NextcloudCookie
        #- "traefik.http.routers.nextcloud.tls=true"
        #- "traefik.http.routers.nextcloud.tls.certresolver=leresolver"
        #- "traefik.http.routers.nextcloud_route.tls=true"
        #- "traefik.http.routers.nextcloud.middlewares=nextcloud_proto"
        #- "traefik.http.services.VCC_stack_nextcloud.loadbalancer.server.port=8081"
        #- "traefik.http.middlewares.nextcloud_proto.headers.customrequestheaders.X-Forwarded-Proto=https" 

  integrator:
    image: 10.255.255.10:5000/integrator
    environment: 
      NEXTCLOUD_CONTAINER_NAME: VCC_stack_nextcloud
      KEYCLOAK_CONTAINER_NAME: VCC_stack_keycloak
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      SAMPLE_USER_PASSWORD: itsdifficult
      OIDC_CLIENT_ID: nextcloud 
      OIDC_PROVIDER_URL: http://10.255.255.10:8080/realms/vcc
      OIDC_LOGOUT_URL: http://10.255.255.10/apps/oidc_login/oidc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - keycloak
      - nextcloud 
    networks:
      - traefik-public
    deploy:
      mode: replicated
      placement:
        constraints:
          - "node.role==manager"
      replicas: 1
      restart_policy:
        condition: on-failure

  reverse-proxy-https-init:
    image: 10.255.255.10:5000/rev-proxy
    environment: 
     SSL_CN: "*.local"
     SSL_O: "VCC"
     SSL_C: "IT"
     SSL_DAYS: 3650
    volumes:
      - /data/certs:/etc/ssl/traefik
      - /data/traefik:/etc/traefik/dynamic
    networks:
      - traefik-public
    deploy:
      restart_policy:
        condition: none
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager      

  traefik:
    image: traefik:v2.9.6
    hostname: traefik
    volumes:
      - /data/certs:/etc/ssl/traefik
      - /data/traefik:/etc/traefik/dynamic
      - ./logs/traefik:/logs/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - /data/traefik/acme.json:/le/acme.json
      # - ./volumes/traefik-config/config.yml:/etc/traefik/traefik.yml
    networks:
      - traefik-public
    ports:
      # HTTP port
      #- target: 80
      #  published: 80
      #  mode: host
      #- target: 443
      #  published: 443
      #  mode: host
      - 80:80
      - 6880:8080
      #  Web UI (enabled by --api.insecure=true)
    depends_on:
      - reverse-proxy-https-init
      - integrator  
    command:
    # enable Web UI
      - --api.insecure=true
      # set provider (Docker Swarm)
      - --providers.docker
      - --providers.docker.swarmMode=true
      - --providers.docker.network=VCC_stack_default
      # traefik http entrypoint port
      - --entrypoints.web.address=:80
      #- --entrypoints.websecure.address=:443
      #- --entrypoints.web.http.redirections.entryPoint.to=websecure
      # add x-forwaded-for
      #- --entrypoints.web.forwardedHeaders.insecure=true
      # manually enable services exposed by traefik
      - --providers.docker.exposedByDefault=false
      #- --certificatesresolvers.leresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      #- --certificatesresolvers.leresolver.acme.email=simoaqui2000@gmail.com
      # Make sure the this file is available and permission is set correctly
      #- --certificatesresolvers.leresolver.acme.storage=/le/acme.json
      #- --certificatesresolvers.leresolver.acme.tlsChallenge=true
      - "--log.filePath=/logs/traefik.log"
      - --accesslog=true
      - "--accesslog.filePath=/logs/access.log"
      - --log.level=DEBUG
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  traefik-public:
    driver: overlay
    name: traefik-public
    attachable: true