---
- name: Common part of the playbook for both nodes
  hosts: all
  become: true
  roles:
  #- docker
  #- monitoring
  #- logging
  #- dashboard

- name: NFS server, Swarm cluster and registry init
  hosts: nfs-servers
  become: true
  roles:
  #  - nfs-server
  #  - docker_swarm-manager
  #  - registry
    
- name: NFS client and Swarm worker join
  hosts: nfs-clients
  become: true
  roles:
    # - nfs-client
    # - docker_swarm-worker
    

- name: Instructing Docker hosts to trust TLS certificate and log into registry
  hosts: all
  become: true
  roles:
    # - registry-tls-common
    # - registry-login
    

- name: Traefik setup
  hosts: nfs-servers
  become: true
  roles:
    # - traefik

- name: Database, Keycloak, Nextcloud and Nextcloud Keycloak Integrator
  hosts: nfs-servers
  become: true
  roles:
    # - database
    - nextcloud
    - stack
    