---
- name: Common part of the playbook for both nodes
  hosts: all
  become: true
  roles:
  - docker
  - database
  - keycloak
  - nextcloud
  - monitoring
  - logging
  - dashboard

- hosts: nfs-servers
  become: true
  roles:
    - nfs-server
    - docker_swarm-manager
    - registry
  
- hosts: nfs-clients
  become: true
  roles:
    - nfs-client
    - docker_swarm-worker 
    - registry-client

- name: Instructing Docker hosts to trust TLS certificate
  hosts: all
  become: true
  roles:
  - registry-tls-common    