---
- name: Common part of the playbook for both nodes
  hosts: all
  become: true
  roles:
    - docker

- name: NFS server, Swarm cluster and registry init
  hosts: nfs-servers
  become: true
  roles:
    - nfs_server
    - docker_swarm_manager

- name: NFS client and Swarm worker join
  hosts: nfs-clients
  become: true
  roles:
    - nfs_client
    - docker_swarm_worker

- name: Prepare all files for the stack
  hosts: all
  become: true
  vars_files:
    - "{{ playbook_dir }}/my_secrets/secrets.yml"
  roles:
    - prometheus_common

- name: Prepare all files for the stack
  hosts: nfs-servers
  become: true
  vars_files:
    - "{{ playbook_dir }}/my_secrets/secrets.yml"
  roles:
    - prepare_stack

- name: Registry Init
  hosts: nfs-servers
  become: true
  vars_files:
    - "{{ playbook_dir }}/my_secrets/secrets.yml"
  roles:
    - registry

- name: Instructing Docker hosts to trust TLS certificate and log into registry
  hosts: all
  become: true
  vars_files:
    - "{{ playbook_dir }}/my_secrets/secrets.yml"
  roles:
    - registry_login

- name: Traefik setup
  hosts: nfs-servers
  become: true
  roles:
    - traefik

- name: Prepare Database and Nextcloud
  hosts: nfs-servers
  become: true
  vars_files:
    - "{{ playbook_dir }}/my_secrets/secrets.yml"
  roles:
    - database
    - keycloak
    - nextcloud

- name: Prepare Logging
  hosts: all
  become: true
  roles:
    - logging

- name: Deploy all services
  hosts: nfs-servers
  become: true
  vars_files:
    - "{{ playbook_dir }}/my_secrets/secrets.yml"
  roles:
    - stack
