version: 0.1
log:
  fields:
    service: registry-cache
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /docker-registry
http:
  addr: :5001
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /certs/fullchain.pem
    key: /certs/privkey.pem
proxy:
  remote_url: https://registry-1.docker.io
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
