global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'dockerswarm'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        regex: .+
        action: keep
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        target_label: job

  - job_name: 'node1 exporter'
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.50.10:9323"]

  - job_name: 'node2 exporter'
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.50.20:9323"]