---
- name: Create postgres data directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: node1
    group: node1
    #recurse: true
    mode: '0755'
  with_items:
    - "{{ postgres_data_dir }}"
    - "{{ postgres_scripts_dir }}"  

- name: Copy initial scripts into NFS dir
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ postgres_scripts_dir }}"
    follow: yes
    mode: '0755'
  with_items:
    - "{{ playbook_dir }}/examples/postgres/sql/keycloak.sql"
    - "{{ playbook_dir }}/examples/postgres/sql/nextcloud.sql"

- name: Delete env to allow updates
  ansible.builtin.file:
    path: "{{ playbook_dir }}/.env"
    state: absent 

- name: Update env variables for Compose
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/.env"
    state: present
    line: "PLAYBOOK_DIR={{ playbook_dir }}"
    create: yes