version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /docker-registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /certs/fullchain.pem
    key: /certs/privkey.pem  
auth:
  htpasswd:
    realm: registry_realm
    path: /docker-registry/htpasswd
#proxy:
#  remote_url: https://registry-1.docker.io
#  username: username
#  password: password     
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3