---
- name: Create nextcloud data directory if it does not exist
  ansible.builtin.file:
    path: "{{ data_vol }}"
    state: directory
    mode: '0755'

- name: Erase nextcloud image in order to re-execute entrypoint.sh
  community.docker.docker_image:
    build:
      path: "{{ shared_volumes }}/nextcloud/container/"
      nocache: true
    name: "{{ registry_url }}:{{ registry_port }}/nextcloud"
    source: build
    state: absent
    force_absent: true

- name: Build an image and push it to a private repo
  community.docker.docker_image:
    build:
      path: "{{ shared_volumes }}/nextcloud/container/"
      nocache: true
    name: "{{ registry_url }}:{{ registry_port }}/nextcloud"
    push: true
    source: build
    debug: true