---
data_dir: "{{ nfs_share_path }}/docker-registry"
certs_dir: "{{ data_dir }}/certs"
psw_file: "{{ data_dir }}/user_psw.txt"
registry_htpasswd_file: "{{ data_dir }}/htpasswd"
registry_realm: registry_realm
registry_username: registry_user