---
- name: Build an image and push it to a private repo
  community.docker.docker_image:
    build:
      path: "{{playbook_dir}}/examples/nextcloud-keycloak-integrator/container"
    name: 10.255.255.10:5000/nextcloud-keycloak-integrator
    push: true
    source: build