---
- name: Create directories needed for logging if they do not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
    recurse: true
  with_items:
    - "/volumes/fluent-bit/"

- name: "Render fluent-bit.conf file using variables"
  ansible.builtin.template:
    src: "{{ playbook_dir }}/volumes/fluent-bit/fluent-bit.j2"
    dest: "/volumes/fluent-bit/fluent-bit.conf"
    mode: '0777'
