---
- name: Create certificates directory if it does not exist
  ansible.builtin.file:
    path: "{{ docker_tls }}"
    state: directory
    mode: '0755'

- name: Instructing a single Docker host to trust TLS certificate
  ansible.builtin.copy:
    src: "{{ src_path }}"
    dest: "{{ docker_tls }}/ca.crt"  # link to /path/to/file
    follow: true
    remote_src: true
    mode: '0777'

- name: Waiting for registry to be up
  ansible.builtin.wait_for:
    host: "{{ registry_url }}"
    port: "{{ registry_port }}"
    delay: 5
    state: started

- name: Log into private registry with TLS and client certificates
  community.docker.docker_login:
    registry_url: "https://{{ registry_url }}:{{ registry_port }}"
    tls: true
    ca_cert: "{{ certs_dir }}/fullchain.pem"
    client_cert: "{{ certs_dir }}/fullchain.pem"
    client_key: "{{ certs_dir }}/privkey.pem"
    username: "{{ REGISTRY_USER }}"
    password: "{{ REGISTRY_PASS }}"
    tls_hostname: myregistry.domain.com
    reauthorize: true
    validate_certs: true
  register: login_result
  retries: 10
  delay: 10
  until: login_result is success
