---
- name: Create certificates directory if it does not exist
  ansible.builtin.file:
    path: "{{ docker_tls }}"
    state: directory
    mode: '0755'

- name: Instructing a single Docker host to trust TLS certificate
  ansible.builtin.copy:
    src: "{{ src_path }}"
    dest: "{{ docker_tls }}/ca.crt"  # link to /path/to/file
    follow: yes
    remote_src: true

- name: Log into private registry with TLS and client certificates
  community.docker.docker_login:
    registry_url: "https://{{ registry_url }}:{{ registry_port }}"
    tls: yes
    ca_cert: "{{ certs_dir }}/fullchain.pem"
    client_cert: "{{ certs_dir }}/fullchain.pem"
    client_key: "{{ certs_dir }}/privkey.pem"
    username: "{{ REGISTRY_USER }}"
    password: "{{ REGISTRY_PASS }}"
    tls_hostname: myregistry.domain.com
    reauthorize: true
    validate_certs: true
  register: login_result
  retries: 5
  delay: 2
  until: login_result is success  