api:
  insecure: true

log:
  level: DEBUG
  filePath: /logs/traefik.log

accesslog:
  filePath: /logs/access.log

providers:
  docker:
    exposedByDefault: false
    swarmMode: true
    network: VCC_stack_default

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
    forwardedHeaders:
      insecure: true      
  websecure:
    address: :443

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/ssl/traefik/server.crt
        keyFile: /etc/ssl/traefik/server.key
  certificates:
    - certFile: /etc/ssl/traefik/server.crt
      keyFile: /etc/ssl/traefik/server.key