---
# each element is a task
- name: Install NFS client # task name (useful for log)
  ansible.builtin.apt:
    name: nfs-common

- name: "Create NFS mount directory {{ nfs_share_path }}"
  ansible.builtin.file:
    path: "{{ nfs_share_path }}"
    state: directory
    mode: '0755'

- name: Mount NFS
  ansible.posix.mount:
    src: "{{ hostvars[ groups['nfs-servers'] | first ]['ansible_host'] }}:{{ nfs_share_path }}"
    path: "{{ nfs_share_path }}"
    opts: rw
    fstype: nfs
    state: mounted
