---
- name: Create or modify docker daemon
  copy:
    dest: "{{ daemon_file }}"
    content: |
      {{ daemon_content }}

- name: Restart Docker service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker