---
- name: Create or modify docker daemon
  ansible.builtin.copy:
    dest: "{{ daemon_file }}"
    content: |
      {{ daemon_content }}
    mode: '0777'

- name: Restart Docker service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: docker
